### PR TITLE
added computer choice, player input checking

### PR DESCRIPTION
**Pull request by pepk0**
I made the computer choice option and fixed some checking from the player input. The player input was checked if it was a list, not if it was in the list, also added a text output(Thanks for playing) when exiting. Also added additional print with the computer choice.

### CODE REVIEW

**Comment by IvanBonev89** [comment]
Your code is great, Pepi. Thank you. I will try to continue a little and I will send it to you.

**Comment by pepk0** [comment]
Could you try to accept the pull request so we can learn?

**Comment by IvanBonev89** [comment]
I have a pull request (1)... but I don't see a button for any action to accept it.

**Comment by pepk0** [comment]
There should be a button Merge pull request somewhere da

**Pull request merged**
